# Generated by Django 5.1.5 on 2025-02-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTimeApp', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
