# Generated by Django 5.1.7 on 2025-05-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTimeApp', '0002_alter_customuser_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumthread',
            name='author',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='ForumThread',
        ),
    ]
