# Generated by Django 5.1.7 on 2025-04-22 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTimeApp', '0005_alter_event_options_alter_lastevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='last_event_images/')),
                ('last_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workoutTimeApp.lastevent')),
            ],
        ),
    ]
