# Generated by Django 5.1.7 on 2025-04-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTimeApp', '0006_lasteventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastevent',
            name='description',
            field=models.TextField(null='true', verbose_name='Описание поста'),
            preserve_default='true',
        ),
    ]
