# Generated by Django 5.1.7 on 2025-04-22 02:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTimeApp', '0008_alter_lastevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(null='true', verbose_name='Описание поста'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(null='true', verbose_name='Описание'),
        ),
    ]
